version: '3.8'
services:
  flask-app:
    image: 339713055661.dkr.ecr.us-east-1.amazonaws.com/employee-flask:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      mysql_db:
        condition: service_healthy
    container_name: flask-app
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DATABASE: flask_app_db

  mysql_db:
    image: 339713055661.dkr.ecr.us-east-1.amazonaws.com/mysql_db:latest
    build:
      context: .
      dockerfile: mysql/Dockerfile.mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: "*snuggy_14"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  mysql_data:
